version: '3'
services:
  rabbitmq:
    image: rabbitmq
    ports:
      - "9672:5672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "is_running"]
      interval: 30s
      timeout: 10s
      retries: 5

  elasticsearch:
    image: elasticsearch:7.0.0
    ports:
      - "9200:9200"
      - "9300"
    environment:
      discovery.type: single-node

  minio:
    image: minio/minio
    ports:
      - "9000:9000"
    links:
      - rabbitmq
    environment:
      MINIO_ACCESS_KEY: demo
      MINIO_SECRET_KEY: secret-key
    volumes:
      - ./data:/data
    depends_on:
      - rabbitmq
      - elasticsearch
    command: server /data

  checksum:
    build:
      context: .
      dockerfile: Dockerfile.checksum
    links:
      - rabbitmq
      - elasticsearch
      - minio
    depends_on:
      - rabbitmq
      - elasticsearch
      - minio
    environment:
      MINIO_HOST: minio
      MINIO_PORT: 9000
      MINIO_ACCESS_KEY: demo
      MINIO_SECRET_KEY: secret-key
      AMQP_HOST: rabbitmq
      ELASTICSEARCH_HOST: elasticsearch:9200

  checksum_download:
    build:
      context: .
      dockerfile: Dockerfile.checksum
    ports:
      - "5005:8000"
    links:
      - elasticsearch
      - minio
    depends_on:
      - elasticsearch
      - minio
    environment:
      MINIO_HOST: minio
      MINIO_PORT: 9000
      MINIO_ACCESS_KEY: demo
      MINIO_SECRET_KEY: secret-key
      MINIO_PORT: 9000
      AMQP_HOST: rabbitmq
      ELASTICSEARCH_HOST: elasticsearch:9200
    entrypoint: gunicorn -b 0.0.0.0:8000 checksum_service.wsgi:app

  metadata:
    build:
      context: .
      dockerfile: Dockerfile.metadata
    links:
      - rabbitmq
      - elasticsearch
      - minio
    depends_on:
      - rabbitmq
      - elasticsearch
      - minio
    environment:
      MINIO_HOST: minio
      MINIO_PORT: 9000
      MINIO_ACCESS_KEY: demo
      MINIO_SECRET_KEY: secret-key
      AMQP_HOST: rabbitmq
      ELASTICSEARCH_HOST: elasticsearch:9200

  kibana:
    image: docker.elastic.co/kibana/kibana:7.0.0
    ports:
      - "5601:5601"
    links:
      - elasticsearch
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
